version: 4.4.{build}
branches:
  only:
    - master
pull_requests:
  do_not_increment_build_number: true
skip_tags: true
image: Visual Studio 2019
clone_depth: 1
build_script:
- cmd: Src\Setup\__MakeFinal.bat
test: off
only_commits:
  files:
    - Src/
    - Localization/
deploy:
- provider: GitHub
  tag: v$(APPVEYOR_BUILD_VERSION)
  release: $(APPVEYOR_BUILD_VERSION)
  on:
    APPVEYOR_ACCOUNT_NAME: passionate-coder
  auth_token:
    secure: 01CsOFRdj9KFb1hp/RlFK/F1UzGhzwGQfok6OoqcL1ipbOwRF//Phbdm7iaFVWIx
  prerelease: true
